# Default configuration for MNIST Classifier
training_function: ml.training.classifier_training.classifier_training.training_loop

# Model architecture parameters
training_config:
  epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0001
  log_interval: 100
