[project]
name = "ml-infra"
version = "0.0.1"
description = "ML Infrastructure Project"
requires-python = ">=3.11"
dependencies = [
    "torch==2.8.0",
]

[project.scripts]
submit = "submit.cli:main"
